---
AWSTemplateFormatVersion: 2010-09-09
Description: Helewski Stack to deploy aws items and services.
Parameters:
  EnvironmentName:
    Description: The environment name that will be prefixed to resource names.
    Type: String
    Default: helewski
Resources:
  SkeletonStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/helewski-cf-templates/helewski-skeleton-stack.yml
      Parameters:
        EnvironmentName:
          !Ref EnvironmentName
  Route53Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/helewski-cf-templates/helewski-route53-stack.yml
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/helewski-cf-templates/helewski-bastion-stack.yml
      Parameters:
        EnvironmentName:
          !Ref EnvironmentName
        VpcId:
          !GetAtt [ SkeletonStack, Outputs.VpcId ]
        CidrBlock:
          !GetAtt [ SkeletonStack, Outputs.CidrBlock ]
        SubnetsPublic:
          !GetAtt [ SkeletonStack, Outputs.SubnetsPublic ]
        PublicHostedZoneName:
          !GetAtt [ Route53Stack, Outputs.PublicHostedZoneName ]
        PublicHostedZoneId:
          !GetAtt [ Route53Stack, Outputs.PublicHostedZoneId ]
